name: emvqrcode
description: a dart package for decode and encode emv QR code
version: 1.0.5
homepage: https://github.com/LaoitdevOpen/dart-emv-code

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
dependencies: 
  convert: ^3.0.1
  crclib: ^3.0.0